### ISSUE TITLE
Installed plugin, but not showing up in add-on list.

### ISSUE THREAD

**Issue by erh** [alessandro-zomparelli/myfacemask#1]
I have Blender 2.82 installed and have followed the instructions to install the plugin.
The Blender logs say that the plugin is installed but then it doesn't appear in the add-on list.
Any ideas?
Have tried or mac os x, and windows.

`Modules Installed () from '/Users/erh/Downloads/MY-FACE-MASK_INSTRUCTION_03-1.zip' into '/Users/erh/Library/Application Support/Blender/2.82/scripts/addons'
`

**Comment by alessandro-zomparelli** [comment]
Hi @erh , I think you selected the zip file that contains several materials and instructions, not the add-on. Please donwload lo zip here from github.

**Comment by erh** [comment]
Got it, might want to update instructions a little to make that a little clearer.
Thanks!

**Comment by alessandro-zomparelli** [comment]
Yes, you are probably right. I'll try to make it more clear.
