### ISSUE TITLE
Filter ring missing

### ISSUE THREAD

**Issue by afkool** [alessandro-zomparelli/myfacemask#2]
I used the plugin and created a mask however, I can't seem to figure out how to get the filter ring model created so it can be printed.  I've read through the PDFs and WASP website but it skips that part.  Am I missing something obvious or is it not available?

Thanks

**Comment by alessandro-zomparelli** [comment]
Hi @afkool , you should find the STL in this ZIP file: https://www.3dwasp.com/en/download/download-info/my-mask-3d-printed-mask-from-3d-scanning/

**Comment by afkool** [comment]
Thanks for the pointer, I see it now.

Also thank you very much for the quick response and providing this plugin.
