### ISSUE TITLE
The menu is imcomplete

### ISSUE THREAD

**Issue by alvaro562003** [alessandro-zomparelli/myfacemask#7]
Hello,
I install Myfacemask on blender 2.82 and i have an incomplete menu for the 1 test.
On the left of the image: What i am expecting
On the right of the image: What i really get
 
![MyMassk_0](https://user-images.githubusercontent.com/10100540/80856499-dce9cd80-8c4a-11ea-878d-772e74c219d7.png)

Regards

**Comment by alvaro562003** [comment]
I solve my problem by re-installing  blender 2.82 and your addon.

Excellent job

**Comment by alessandro-zomparelli** [comment]
Great, thanks! I'll close the issue
